# Generated by Django 5.0.3 on 2024-12-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
